version: "3.7"

services:
    miner-runner:
        #pull_policy: never
        #build:
        #    context: .
        image: CoinfarmVentures/compute-subnet-miner-runner:local
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "$HOME/.bittensor/wallets:/root/.bittensor/wallets"
            - ./.env:/root/miner/.env
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        network_mode: "host"

    # watchtower:
    #   image: containrrr/watchtower:1.7.1
    #   restart: unless-stopped
    #   volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock
    #   command: --interval 60 --cleanup --label-enable
