version: "3.7"

services:
    db:
        image: postgres:14.0-alpine
        healthcheck:
            test: pg_isready -U postgres || exit 1
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        expose:
            - 5432
        env_file: ./.env
        volumes:
            - db_data:/var/lib/postgresql/data

    miner:
        pull_policy: never
        build:
            context: .
        image: CoinfarmVentures/compute-subnet-miner:local
        env_file: ./.env
        ports:
            - ${EXTERNAL_PORT}:${INTERNAL_PORT}
            - 5679:5679
        expose:
            - ${INTERNAL_PORT}
            - 5679
        environment:
            - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        volumes:
            - ${HOST_WALLET_DIR}:/root/.bittensor/wallets
        depends_on:
            - db

volumes:
    db_data:
